language: python
python:
  - "2.7.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install requests responses coveralls
script: nosetests -v --with-coverage --cover-package=razorpay
after_success: coveralls
