# Generated by Django 3.2 on 2021-06-04 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Referral offer', max_length=20)),
                ('cupon_code', models.CharField(max_length=50, unique=True)),
                ('offer_price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('taken_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_cupon_taken_user', to=settings.AUTH_USER_MODEL)),
                ('which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_user_signup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Referral offer', max_length=20)),
                ('cupon_code', models.CharField(max_length=50, unique=True)),
                ('offer_price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('taken_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_user', to=settings.AUTH_USER_MODEL)),
                ('which_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Today special offer', max_length=20)),
                ('offer_percentage', models.PositiveIntegerField()),
                ('date_period', models.DateField()),
                ('time_period', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_panel.product')),
            ],
        ),
        migrations.CreateModel(
            name='CuponOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Today special offer', max_length=20)),
                ('cupon_code', models.CharField(max_length=50, unique=True)),
                ('offer_price', models.PositiveIntegerField()),
                ('date_period', models.DateField()),
                ('time_period', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupon_taken_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Today special offer', max_length=20)),
                ('offer_percentage', models.PositiveIntegerField()),
                ('date_period', models.DateField()),
                ('time_period', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_panel.category')),
            ],
        ),
    ]
