# Generated by Django 3.2 on 2021-05-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_panel', '0024_product_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon_or_Referral_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_code', models.CharField(max_length=15)),
                ('offer_percentage', models.PositiveIntegerField(max_length=2)),
                ('time_period', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_percentage', models.PositiveIntegerField(max_length=2)),
                ('time_period', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_percentage', models.PositiveIntegerField(max_length=2)),
                ('time_period', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel.category')),
            ],
        ),
    ]
