# Generated by Django 3.2 on 2021-05-23 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20210523_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='date_period',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='time_period',
            field=models.TimeField(),
        ),
    ]
