# Generated by Django 3.2 on 2021-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20210523_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Today special offer', max_length=20)),
                ('cupon_code', models.CharField(max_length=15)),
                ('offer_percentage', models.PositiveIntegerField()),
                ('date_period', models.DateField()),
                ('time_period', models.TimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CuponOrReferralOffer',
        ),
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='offer_percentage',
            new_name='offer_price',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='date_period',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='time_period',
            field=models.TimeField(),
        ),
    ]
