# Generated by Django 3.2 on 2021-05-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20210525_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='offer_price',
            new_name='offer_percentage',
        ),
        migrations.RenameField(
            model_name='cuponoffer',
            old_name='offer_percentage',
            new_name='offer_price',
        ),
    ]
