# Generated by Django 3.2 on 2021-05-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20210526_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponoffer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
