# Generated by Django 3.2 on 2021-05-29 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0011_remove_cuponoffer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cupon_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cuponoffer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
