# Generated by Django 3.2 on 2021-05-30 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0013_cuponoffer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponoffer',
            name='recommended_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_usere', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuponoffer',
            name='signup_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cuponoffer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupon_taken_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
