# Generated by Django 3.2 on 2021-05-30 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0014_auto_20210530_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Referral offer', max_length=20)),
                ('cupon_code', models.CharField(max_length=50, unique=True)),
                ('offer_price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('taken_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_user', to=settings.AUTH_USER_MODEL)),
                ('which_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignupCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_for', models.CharField(default='Referral offer', max_length=20)),
                ('cupon_code', models.CharField(max_length=50, unique=True)),
                ('offer_price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('taken_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_cupon_taken_user', to=settings.AUTH_USER_MODEL)),
                ('which_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_user_signup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cuponoffer',
            name='recommended_user',
        ),
        migrations.RemoveField(
            model_name='cuponoffer',
            name='signup_user',
        ),
        migrations.AlterField(
            model_name='cuponoffer',
            name='cupon_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='CuponTaken',
        ),
    ]
