# Generated by Django 3.2 on 2021-05-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='confirm_password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
