# Generated by Django 3.2 on 2021-05-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usermobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobilenumber',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
