# Generated by Django 3.2 on 2021-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usermobilenumber_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobilenumber',
            name='mobile_no',
            field=models.CharField(max_length=13),
        ),
    ]
