# Generated by Django 3.2 on 2021-06-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile_number', models.CharField(max_length=12)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=245)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('UP', 'UP'), ('Tamilnad', 'Tamilnad')], max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='user_panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_imgs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='prd_imgs')),
                ('more_image_one', models.ImageField(upload_to='prd_imgs')),
                ('more_image_two', models.ImageField(upload_to='prd_imgs')),
                ('more_image_three', models.ImageField(upload_to='prd_imgs')),
                ('marked_price', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('product_offer_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('category_offer_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('guarandeed', models.BooleanField()),
                ('description', models.TextField()),
                ('model_number', models.CharField(blank=True, max_length=10, null=True)),
                ('model_name', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Black', 'Black'), ('Red', 'Red')], max_length=20, null=True)),
                ('battery_backup', models.CharField(blank=True, default='Upto 3 hours', max_length=15, null=True)),
                ('processor_brand', models.CharField(blank=True, max_length=15, null=True)),
                ('processor_name', models.CharField(blank=True, max_length=15, null=True)),
                ('storage', models.CharField(blank=True, choices=[('64GB', '64GB'), ('128GB', '128GB'), ('512GB', '512GB')], max_length=15, null=True)),
                ('ram', models.CharField(blank=True, choices=[('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB')], max_length=15, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_catg', to='user_panel.subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_catg', to='user_panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('paypal', 'paypal'), ('razorpay', 'razorpay'), ('cod', 'cod')], max_length=20)),
                ('order_status', models.CharField(choices=[('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_price', models.PositiveIntegerField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('time_stamp', models.DateField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.product')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_total', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_panel.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
