# Generated by Django 3.2 on 2021-05-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='user_panel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='prd_imgs')),
                ('marked_price', models.PositiveIntegerField()),
                ('selling_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('model_number', models.CharField(blank=True, max_length=10, null=True)),
                ('model_name', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('battery_backup', models.CharField(blank=True, default='Upto 3 hours', max_length=15, null=True)),
                ('processor_brand', models.CharField(blank=True, max_length=15, null=True)),
                ('processor_name', models.CharField(blank=True, max_length=15, null=True)),
                ('storage', models.CharField(blank=True, max_length=15, null=True)),
                ('ram', models.CharField(blank=True, max_length=15, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_catg', to='user_panel.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_catg', to='user_panel.subcategory')),
            ],
        ),
    ]
