# Generated by Django 3.2 on 2021-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guarandeed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='more_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='prd_imgs'),
        ),
        migrations.AddField(
            model_name='product',
            name='more_image_three',
            field=models.ImageField(blank=True, null=True, upload_to='prd_imgs'),
        ),
        migrations.AddField(
            model_name='product',
            name='more_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='prd_imgs'),
        ),
    ]
