# Generated by Django 3.2 on 2021-05-07 07:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20210504_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, choices=[('#FFFF', 'white'), ('#0000', 'Black')], default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, choices=[('4GB', '4GB'), ('8GB', '8GB')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, choices=[('64GB', '64GB'), ('128GB', '128GB')], max_length=15, null=True),
        ),
    ]
