# Generated by Django 3.2 on 2021-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_auto_20210507_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_image_one',
            field=models.ImageField(default=1, upload_to='prd_imgs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='more_image_three',
            field=models.ImageField(default=1, upload_to='prd_imgs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='more_image_two',
            field=models.ImageField(default=1, upload_to='prd_imgs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, choices=[('4GB', '4GB'), ('8GB', '8GB'), ('8GB', '8GB')], max_length=15, null=True),
        ),
    ]
