# Generated by Django 3.2 on 2021-05-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0010_auto_20210509_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
