# Generated by Django 3.2 on 2021-05-10 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0011_cartitem_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('address', models.CharField(max_length=245)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('UP', 'UP'), ('Tamilnad', 'Tamilnad')], max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=5)),
            ],
        ),
    ]
