# Generated by Django 3.2 on 2021-05-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
