# Generated by Django 3.2 on 2021-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0017_auto_20210513_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
