# Generated by Django 3.2 on 2021-05-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0019_auto_20210513_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Black', 'Black')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, choices=[('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB')], max_length=15, null=True),
        ),
    ]
