# Generated by Django 3.2 on 2021-05-17 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0020_auto_20210516_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('paypal', 'paypal'), ('razorpay', 'razorpay'), ('cod', 'cod')], max_length=20),
        ),
    ]
