# Generated by Django 3.2 on 2021-05-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0021_auto_20210517_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_stamp',
            field=models.DateField(),
        ),
    ]
