# Generated by Django 3.2 on 2021-05-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0023_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
