# Generated by Django 3.2 on 2021-05-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0026_alter_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Black', 'Black')], max_length=20, null=True),
        ),
    ]
