# Generated by Django 3.2 on 2021-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0027_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Black', 'Black'), ('Red', 'Red')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, choices=[('64GB', '64GB'), ('128GB', '128GB'), ('512GB', '512GB')], max_length=15, null=True),
        ),
    ]
