# Generated by Django 3.2 on 2021-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0028_auto_20210525_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer_price',
            new_name='category_offer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
